version: '3.4'
services:
  postgres:
    build:
      context: postgresql/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/usr/share/postgres/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
    driver: local
