CREATE TABLE APP_USER
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255),
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    email         VARCHAR(255),
    password      VARCHAR(255),
    gender        VARCHAR(255),
    date_of_birth TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

ALTER TABLE APP_USER
    ADD CONSTRAINT uc_app_user_email UNIQUE (email);

CREATE TABLE PRODUCT
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_type   VARCHAR(255),
    name          VARCHAR(255),
    accessibility VARCHAR(255),
    amount        INTEGER,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

INSERT INTO PRODUCT(id, product_type, name, accessibility, amount)
VALUES (1, 'CALLS_AND_PACKAGES', 'pausal1', 'UNLIMITED', NULL),
       (2, 'CALLS_AND_PACKAGES', 'pausal2', 'UNLIMITED', NULL),
       (3, 'INTERNET_AND_TV', 'internet_package1', 'UNLIMITED', NULL),
       (4, 'INTERNET_AND_TV', 'internet_package2', 'UNLIMITED', NULL),
       (5, 'CELLPHONES_AND_DEVICES', 'Apple Iphone 14 PRO 256GB BLACK', 'LIMITED', 10),
       (6, 'CELLPHONES_AND_DEVICES', 'Apple Iphone 14 PRO 512GB BLACK', 'LIMITED', 5);
