CREATE TABLE APP_USER
(
    user_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username         VARCHAR(255),
    first_name       VARCHAR(255),
    last_name        VARCHAR(255),
    email            VARCHAR(255),
    password         VARCHAR(255),
    gender           VARCHAR(255),
    date_of_birth    TIMESTAMP WITHOUT TIME ZONE,
    street           VARCHAR(255),
    residence_number INTEGER,
    city             VARCHAR(255),
    postal           VARCHAR(255),
    CONSTRAINT pk_app_user PRIMARY KEY (user_id)
);

ALTER TABLE APP_USER
    ADD CONSTRAINT uc_app_user_email UNIQUE (email);

ALTER TABLE APP_USER
    ADD CONSTRAINT uc_app_user_username UNIQUE (username);

CREATE TABLE PRODUCT
(
    product_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_type  VARCHAR(255),
    name          VARCHAR(255),
    accessibility VARCHAR(255),
    amount        INTEGER,
    price         DOUBLE PRECISION,
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

CREATE TABLE APP_ORDER
(
    order_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    status     VARCHAR(255),
    total_price DOUBLE PRECISION,
    created    TIMESTAMP WITHOUT TIME ZONE,
    modified   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_app_order PRIMARY KEY (order_id)
);

ALTER TABLE APP_ORDER
    ADD CONSTRAINT FK_APP_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES APP_USER (user_id);

CREATE TABLE ORDER_PRODUCT
(
    order_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id         BIGINT,
    product_id       BIGINT,
    quantity         INTEGER,
    CONSTRAINT pk_order_product PRIMARY KEY (order_product_id)
);

ALTER TABLE ORDER_PRODUCT
    ADD CONSTRAINT FK_ORDER_PRODUCT_ON_ORDER FOREIGN KEY (order_id) REFERENCES APP_ORDER (order_id);

ALTER TABLE ORDER_PRODUCT
    ADD CONSTRAINT FK_ORDER_PRODUCT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES PRODUCT (product_id);
------------------------------------------------------------------------------------------------------------------
INSERT INTO APP_USER(user_id, username, first_name, last_name, email, password, gender, date_of_birth, street, residence_number,
                     city, postal)
VALUES (1, 'test_username1', 'Test', 'Test', 'test@test.com', 'test1234', 'MALE', '1970-01-01', 'Ilkovicova', 1,
        'Bratislava', '842 16');


INSERT INTO PRODUCT(product_id, product_type, name, accessibility, amount, price)
VALUES (1, 'CALLS_AND_PACKAGES', 'pausal1', 'UNLIMITED', NULL, 20.00),
       (2, 'CALLS_AND_PACKAGES', 'pausal2', 'UNLIMITED', NULL, 30.00),
       (3, 'INTERNET_AND_TV', 'internet_package1', 'UNLIMITED', NULL, 15.00),
       (4, 'INTERNET_AND_TV', 'internet_package2', 'UNLIMITED', NULL, 20.00),
       (5, 'CELLPHONES_AND_DEVICES', 'Apple Iphone 14 PRO 256GB BLACK', 'LIMITED', 10, 1300.00),
       (6, 'CELLPHONES_AND_DEVICES', 'Apple Iphone 14 PRO 512GB BLACK', 'LIMITED', 5, 1500.00);



