CREATE TABLE APP_USER
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255),
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    email         VARCHAR(255),
    password      VARCHAR(255),
    gender        VARCHAR(255),
    date_of_birth TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

ALTER TABLE APP_USER
    ADD CONSTRAINT uc_app_user_email UNIQUE (email);
